### ISSUE TITLE
Support for live reload time delay.

### ISSUE THREAD

**Issue by sethburtonhall** [gruntjs/grunt-contrib-watch#175]
Any chance to add support for an option to delay the browser reload like the Mac app.

**Comment by husanu** [comment]
modify the function from grunt-contrib-watch/tasks/lib/livereload.js file, from:

    LR.prototype.trigger = function(files) {
        grunt.log.verbose.writeln('Live reloading ' + grunt.log.wordlist(files) + '...');
        this.server.changed({body:{files:files}});
    };

to:

    LR.prototype.trigger = function(files) {
        var self = this;
        grunt.log.verbose.writeln('Live reloading ' + grunt.log.wordlist(files) + '...');
        
        setTimeout(function(){
          self.server.changed({body:{files:files}});
        }, 1000);
    };

**Comment by leviwheatcroft** [comment]
not sure if this is an elegant solution or a hacky workaround.. but `grunt-contrib-watch` uses [tiny-lr](https://github.com/mklabs/tiny-lr) which you can trigger via a http request. 

So in my case watch is supposed to reload a webserver which takes a few seconds, rather than just specifying an arbitrary delay of 2 or 3 seconds, you can just have the webserver notify tiny-lr when it's ready like this:

      var http = require('http');
      http.get('http://localhost:35729/changed?files=foo.js');   

A few caveats:

 * in my case `grunt-contrib-watch` is creating the tiny-lr server for me because it's watching css files, if it wasn't for that I'd need to create the server myself.
 * also, doing it this way makes it difficult (impossible?) to pass the changed files to tiny-lr.. but the /changed endpoint doesn't seem to do anything unless you specify a file with the files query value?
