### ISSUE TITLE
Why is grunt.task.run not called in the grunt.event.on("watch") handler?

### ISSUE THREAD

**Issue by LeoYuan** [gruntjs/grunt-contrib-watch#65]
@shama 
Hey, guys, I got two doubts, described as follows,
1. how to pass parameters(let's say filepath) into the specified tasks?

```
watch: {
    views: {
        files: ['source/**.*'],
        tasks: ['myTask']
    }
}
```

myTask will run against the modified file name, without that, myTask does not make sense.
2. because of the first (possibly)defect, so I have to choose this way - grunt.event.on("watch")
**BUT** I found the grunt.task.run is not working inside the watch handler, which means I can not run any tasks defined.

```
grunt.event.on('watch', function(action, filepath) {
    grunt.task.run(['uglify']);
}
```

Could you give me any suggestions, thanks in advance.

**Comment by hholhjem** [comment]
@shama thanks for your informative example above combining watch and jshint in this thread.

I am trying to set up a config where I combine watch and less. I have tried to follow the similar setup as you did with watch and jshint without success.

Is it at all possible to set up watch to work together with less? So that less compiles all .less files that watch "finds"?
