### ISSUE TITLE
Cant not defined task which include a subset of multiple watch tasks

### ISSUE THREAD

**Issue by neekey** [gruntjs/grunt-contrib-watch#71]
The problem is quite simple, I defined my watch tasks like:

```
watch: {
   "a": { files: "...", tasks: [ .. ] },
   "b": { files: "...", tasks: [ .. ] },
   "c": { files: "...", tasks: [ .. ] }
}
```

and after that I want to define a new task which only contain a subset of all the watch tasks:

``` js
grunt.registerTask( 'myWatch', [ 'watch:a', 'watch:c' ] );

```

But it seems like only the first watch subtask works.

**Comment by robertdunaway** [comment]
I'm having the same problem.  If grunt ran faster I wouldn't feel the need to run a subset of watch commands but it does and I do.

I'm disappointed that this topic is so old and so little progress has been made and I get the feeling grunt doesn't change because grunt has always worked a certain way.

Great tool up to this point.  I'm not sure the tool will satisfy my development team anymore, with this limitation.  I'm not comfortable with all the hacks to do something that is obviously needed.

**Comment by shama** [comment]
@robertdunaway Patches welcome.

**Comment by dmcb** [comment]
Thanks for the switchwatch task @shama. That should be default behaviour for watch.

**Comment by intransitorio** [comment]
@stowball `s  solution worked for me. Thanks
